import { Article } from "./article";

export const ARTICLES: Article[] = [
    { 
        title: "Bitcoin, the World's Reserve Currency?",
        tldrs: ["Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque a ex posuere.",
	"Integer eget luctus ex. Nam fermentum quis quam vel sagittis.", 
	"Aliquam semper, sem sit amet luctus pretium, eros justo porttitor dolor, at rutrum quam tellus nec sem.",
	"Etiam eu lacus vitae felis dignissim tincidunt nec nec sem."],
        content: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque a ex posuere, dignissim turpis eget, feugiat nulla. In hac habitasse platea dictumst. Etiam tincidunt vitae nisl congue commodo. Integer tincidunt dolor nisi, ac sollicitudin metus rutrum et. <br><br>"+
	"Ut arcu magna, ultricies ut libero ut, posuere condimentum lorem. Integer eget luctus ex. Nam fermentum quis quam vel sagittis. Aliquam semper, sem sit amet luctus pretium, eros justo porttitor dolor, at rutrum quam tellus nec sem. Etiam eu lacus vitae felis dignissim tincidunt nec nec sem. Vivamus vitae varius ligula. Proin in malesuada ex. In mi mi, dictum at orci in, mattis imperdiet risus. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. <br><br>"+
	"Vestibulum lorem nibh, laoreet interdum magna pretium, laoreet faucibus mauris. Nam suscipit quam ut velit dapibus mollis. In a nunc consequat nulla sollicitudin luctus vitae a justo. Morbi id turpis dapibus, aliquam ligula in, dictum lacus. Praesent id mattis mi. Donec facilisis tristique mi eget pulvinar. Phasellus viverra vehicula ligula, nec imperdiet massa sagittis in. Sed eu leo tempor tortor elementum rutrum at at augue. Suspendisse potenti. Ut quis libero ullamcorper, consequat mauris non, egestas velit. Phasellus vitae pretium mi, non feugiat eros. Vestibulum hendrerit turpis gravida accumsan ullamcorper. Aliquam erat volutpat. Maecenas ornare velit id nisl vehicula, et auctor tellus dictum. Maecenas rhoncus orci ac dolor rhoncus tincidunt. Sed venenatis ac sapien at aliquet. Sed non nunc varius, eleifend lectus sit amet, euismod nibh. Quisque suscipit, orci eu molestie ullamcorper, nulla mi elementum lectus, a faucibus tortor massa eu turpis. <br><br>"+
	"Fusce sollicitudin, massa eu feugiat bibendum, magna dui dictum ante, vitae dictum eros tortor sit amet nulla. Pellentesque consequat sit amet nunc id pellentesque. Praesent in libero vel justo facilisis tincidunt a vitae mi. Cras fermentum urna a orci tincidunt, vitae sollicitudin nulla euismod. Pellentesque ac leo ullamcorper, suscipit elit sed, scelerisque odio. Sed sodales dolor quis ornare pretium. Donec ut viverra nisi, in laoreet ex. Praesent ultrices augue sit amet nunc vehicula, et rutrum metus sagittis. Sed aliquam mattis dolor, a cursus risus posuere vel. <br><br>"+
	"Suspendisse condimentum tellus dui, quis vehicula lacus tempus in. Vestibulum ac orci nec purus faucibus imperdiet. Suspendisse fringilla facilisis mauris non congue. In a ante quis velit ultricies varius a in justo. Donec tincidunt auctor egestas. Donec et felis nec nisi pharetra viverra eu ac metus. Cras euismod nibh eget nibh mollis efficitur sed pulvinar leo. <br><br>"+
	"Aenean vel eros tristique, molestie urna sit amet, mollis urna. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque a ex posuere, dignissim turpis eget, feugiat nulla. In hac habitasse platea dictumst. Etiam tincidunt vitae nisl congue commodo. Integer tincidunt dolor nisi, ac sollicitudin metus rutrum et. Ut arcu magna, ultricies ut libero ut, posuere condimentum lorem. Integer eget luctus ex. Nam fermentum quis quam vel sagittis. Aliquam semper, sem sit amet luctus pretium, eros justo porttitor dolor, at rutrum quam tellus nec sem. Etiam eu lacus vitae felis dignissim tincidunt nec nec sem. <br><br>"+
	"Vivamus vitae varius ligula. Proin in malesuada ex. In mi mi, dictum at orci in, mattis imperdiet risus. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Vestibulum lorem nibh, laoreet interdum magna pretium, laoreet faucibus mauris. Nam suscipit quam ut velit dapibus mollis. In a nunc consequat nulla sollicitudin luctus vitae a justo. Morbi id turpis dapibus, aliquam ligula in, dictum lacus. Praesent id mattis mi. Donec facilisis tristique mi eget pulvinar. Phasellus viverra vehicula ligula, nec imperdiet massa sagittis in. Sed eu leo tempor tortor elementum rutrum at at augue. <br><br>"+
	"Suspendisse potenti. Ut quis libero ullamcorper, consequat mauris non, egestas velit. Phasellus vitae pretium mi, non feugiat eros. Vestibulum hendrerit turpis gravida accumsan ullamcorper. Aliquam erat volutpat. Maecenas ornare velit id nisl vehicula, et auctor tellus dictum. Maecenas rhoncus orci ac dolor rhoncus tincidunt. Sed venenatis ac sapien at aliquet. Sed non nunc varius, eleifend lectus sit amet, euismod nibh. Quisque suscipit, orci eu molestie ullamcorper, nulla mi elementum lectus, a faucibus tortor massa eu turpis. Fusce sollicitudin, massa eu feugiat bibendum, magna dui dictum ante, vitae dictum eros tortor sit amet nulla. <br><br>"+
	"Pellentesque consequat sit amet nunc id pellentesque. Praesent in libero vel justo facilisis tincidunt a vitae mi. Cras fermentum urna a orci tincidunt, vitae sollicitudin nulla euismod. Pellentesque ac leo ullamcorper, suscipit elit sed, scelerisque odio. Sed sodales dolor quis ornare pretium. Donec ut viverra nisi, in laoreet ex. Praesent ultrices augue sit amet nunc vehicula, et rutrum metus sagittis. Sed aliquam mattis dolor, a cursus risus posuere vel. Suspendisse condimentum tellus dui, quis vehicula lacus tempus in. Vestibulum ac orci nec purus faucibus imperdiet. Suspendisse fringilla facilisis mauris non congue. In a ante quis velit ultricies varius a in justo. Donec tincidunt auctor egestas. Donec et felis nec nisi pharetra viverra eu ac metus. <br><br>"+
	"Cras euismod nibh eget nibh mollis efficitur sed pulvinar leo. Aenean vel eros tristique, molestie urna sit amet, mollis urna.",
        date: new Date(),
        author:	"Peter Schiff",
        level: "Nocoiner",
        views: 0,
        likes: 0,
        dislikes: 0
    },
    { 
        title: "Bitcoin, an End to Planned Obsolescence?",
        tldrs: ["Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque a ex posuere.",
	"Integer eget luctus ex. Nam fermentum quis quam vel sagittis.", 
	"Aliquam semper, sem sit amet luctus pretium, eros justo porttitor dolor, at rutrum quam tellus nec sem.",
	"Etiam eu lacus vitae felis dignissim tincidunt nec nec sem."],
        content: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque a ex posuere, dignissim turpis eget, feugiat nulla. In hac habitasse platea dictumst. Etiam tincidunt vitae nisl congue commodo. Integer tincidunt dolor nisi, ac sollicitudin metus rutrum et. <br><br>"+
	"Ut arcu magna, ultricies ut libero ut, posuere condimentum lorem. Integer eget luctus ex. Nam fermentum quis quam vel sagittis. Aliquam semper, sem sit amet luctus pretium, eros justo porttitor dolor, at rutrum quam tellus nec sem. Etiam eu lacus vitae felis dignissim tincidunt nec nec sem. Vivamus vitae varius ligula. Proin in malesuada ex. In mi mi, dictum at orci in, mattis imperdiet risus. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. <br><br>"+
	"Vestibulum lorem nibh, laoreet interdum magna pretium, laoreet faucibus mauris. Nam suscipit quam ut velit dapibus mollis. In a nunc consequat nulla sollicitudin luctus vitae a justo. Morbi id turpis dapibus, aliquam ligula in, dictum lacus. Praesent id mattis mi. Donec facilisis tristique mi eget pulvinar. Phasellus viverra vehicula ligula, nec imperdiet massa sagittis in. Sed eu leo tempor tortor elementum rutrum at at augue. Suspendisse potenti. Ut quis libero ullamcorper, consequat mauris non, egestas velit. Phasellus vitae pretium mi, non feugiat eros. Vestibulum hendrerit turpis gravida accumsan ullamcorper. Aliquam erat volutpat. Maecenas ornare velit id nisl vehicula, et auctor tellus dictum. Maecenas rhoncus orci ac dolor rhoncus tincidunt. Sed venenatis ac sapien at aliquet. Sed non nunc varius, eleifend lectus sit amet, euismod nibh. Quisque suscipit, orci eu molestie ullamcorper, nulla mi elementum lectus, a faucibus tortor massa eu turpis. <br><br>"+
	"Fusce sollicitudin, massa eu feugiat bibendum, magna dui dictum ante, vitae dictum eros tortor sit amet nulla. Pellentesque consequat sit amet nunc id pellentesque. Praesent in libero vel justo facilisis tincidunt a vitae mi. Cras fermentum urna a orci tincidunt, vitae sollicitudin nulla euismod. Pellentesque ac leo ullamcorper, suscipit elit sed, scelerisque odio. Sed sodales dolor quis ornare pretium. Donec ut viverra nisi, in laoreet ex. Praesent ultrices augue sit amet nunc vehicula, et rutrum metus sagittis. Sed aliquam mattis dolor, a cursus risus posuere vel. <br><br>"+
	"Suspendisse condimentum tellus dui, quis vehicula lacus tempus in. Vestibulum ac orci nec purus faucibus imperdiet. Suspendisse fringilla facilisis mauris non congue. In a ante quis velit ultricies varius a in justo. Donec tincidunt auctor egestas. Donec et felis nec nisi pharetra viverra eu ac metus. Cras euismod nibh eget nibh mollis efficitur sed pulvinar leo. <br><br>"+
	"Aenean vel eros tristique, molestie urna sit amet, mollis urna. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque a ex posuere, dignissim turpis eget, feugiat nulla. In hac habitasse platea dictumst. Etiam tincidunt vitae nisl congue commodo. Integer tincidunt dolor nisi, ac sollicitudin metus rutrum et. Ut arcu magna, ultricies ut libero ut, posuere condimentum lorem. Integer eget luctus ex. Nam fermentum quis quam vel sagittis. Aliquam semper, sem sit amet luctus pretium, eros justo porttitor dolor, at rutrum quam tellus nec sem. Etiam eu lacus vitae felis dignissim tincidunt nec nec sem. <br><br>"+
	"Vivamus vitae varius ligula. Proin in malesuada ex. In mi mi, dictum at orci in, mattis imperdiet risus. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Vestibulum lorem nibh, laoreet interdum magna pretium, laoreet faucibus mauris. Nam suscipit quam ut velit dapibus mollis. In a nunc consequat nulla sollicitudin luctus vitae a justo. Morbi id turpis dapibus, aliquam ligula in, dictum lacus. Praesent id mattis mi. Donec facilisis tristique mi eget pulvinar. Phasellus viverra vehicula ligula, nec imperdiet massa sagittis in. Sed eu leo tempor tortor elementum rutrum at at augue. <br><br>"+
	"Suspendisse potenti. Ut quis libero ullamcorper, consequat mauris non, egestas velit. Phasellus vitae pretium mi, non feugiat eros. Vestibulum hendrerit turpis gravida accumsan ullamcorper. Aliquam erat volutpat. Maecenas ornare velit id nisl vehicula, et auctor tellus dictum. Maecenas rhoncus orci ac dolor rhoncus tincidunt. Sed venenatis ac sapien at aliquet. Sed non nunc varius, eleifend lectus sit amet, euismod nibh. Quisque suscipit, orci eu molestie ullamcorper, nulla mi elementum lectus, a faucibus tortor massa eu turpis. Fusce sollicitudin, massa eu feugiat bibendum, magna dui dictum ante, vitae dictum eros tortor sit amet nulla. <br><br>"+
	"Pellentesque consequat sit amet nunc id pellentesque. Praesent in libero vel justo facilisis tincidunt a vitae mi. Cras fermentum urna a orci tincidunt, vitae sollicitudin nulla euismod. Pellentesque ac leo ullamcorper, suscipit elit sed, scelerisque odio. Sed sodales dolor quis ornare pretium. Donec ut viverra nisi, in laoreet ex. Praesent ultrices augue sit amet nunc vehicula, et rutrum metus sagittis. Sed aliquam mattis dolor, a cursus risus posuere vel. Suspendisse condimentum tellus dui, quis vehicula lacus tempus in. Vestibulum ac orci nec purus faucibus imperdiet. Suspendisse fringilla facilisis mauris non congue. In a ante quis velit ultricies varius a in justo. Donec tincidunt auctor egestas. Donec et felis nec nisi pharetra viverra eu ac metus. <br><br>"+
	"Cras euismod nibh eget nibh mollis efficitur sed pulvinar leo. Aenean vel eros tristique, molestie urna sit amet, mollis urna.",
        date: new Date(),
        author:	"Peter Schiff",
        level: "Nocoiner",
        views: 0,
        likes: 0,
        dislikes: 0
    },
    { 
        title: "Fiat, What is Backed by It?",
        tldrs: ["Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque a ex posuere.",
	"Integer eget luctus ex. Nam fermentum quis quam vel sagittis.", 
	"Aliquam semper, sem sit amet luctus pretium, eros justo porttitor dolor, at rutrum quam tellus nec sem.",
	"Etiam eu lacus vitae felis dignissim tincidunt nec nec sem."],
        content: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque a ex posuere, dignissim turpis eget, feugiat nulla. In hac habitasse platea dictumst. Etiam tincidunt vitae nisl congue commodo. Integer tincidunt dolor nisi, ac sollicitudin metus rutrum et. <br><br>"+
	"Ut arcu magna, ultricies ut libero ut, posuere condimentum lorem. Integer eget luctus ex. Nam fermentum quis quam vel sagittis. Aliquam semper, sem sit amet luctus pretium, eros justo porttitor dolor, at rutrum quam tellus nec sem. Etiam eu lacus vitae felis dignissim tincidunt nec nec sem. Vivamus vitae varius ligula. Proin in malesuada ex. In mi mi, dictum at orci in, mattis imperdiet risus. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. <br><br>"+
	"Vestibulum lorem nibh, laoreet interdum magna pretium, laoreet faucibus mauris. Nam suscipit quam ut velit dapibus mollis. In a nunc consequat nulla sollicitudin luctus vitae a justo. Morbi id turpis dapibus, aliquam ligula in, dictum lacus. Praesent id mattis mi. Donec facilisis tristique mi eget pulvinar. Phasellus viverra vehicula ligula, nec imperdiet massa sagittis in. Sed eu leo tempor tortor elementum rutrum at at augue. Suspendisse potenti. Ut quis libero ullamcorper, consequat mauris non, egestas velit. Phasellus vitae pretium mi, non feugiat eros. Vestibulum hendrerit turpis gravida accumsan ullamcorper. Aliquam erat volutpat. Maecenas ornare velit id nisl vehicula, et auctor tellus dictum. Maecenas rhoncus orci ac dolor rhoncus tincidunt. Sed venenatis ac sapien at aliquet. Sed non nunc varius, eleifend lectus sit amet, euismod nibh. Quisque suscipit, orci eu molestie ullamcorper, nulla mi elementum lectus, a faucibus tortor massa eu turpis. <br><br>"+
	"Fusce sollicitudin, massa eu feugiat bibendum, magna dui dictum ante, vitae dictum eros tortor sit amet nulla. Pellentesque consequat sit amet nunc id pellentesque. Praesent in libero vel justo facilisis tincidunt a vitae mi. Cras fermentum urna a orci tincidunt, vitae sollicitudin nulla euismod. Pellentesque ac leo ullamcorper, suscipit elit sed, scelerisque odio. Sed sodales dolor quis ornare pretium. Donec ut viverra nisi, in laoreet ex. Praesent ultrices augue sit amet nunc vehicula, et rutrum metus sagittis. Sed aliquam mattis dolor, a cursus risus posuere vel. <br><br>"+
	"Suspendisse condimentum tellus dui, quis vehicula lacus tempus in. Vestibulum ac orci nec purus faucibus imperdiet. Suspendisse fringilla facilisis mauris non congue. In a ante quis velit ultricies varius a in justo. Donec tincidunt auctor egestas. Donec et felis nec nisi pharetra viverra eu ac metus. Cras euismod nibh eget nibh mollis efficitur sed pulvinar leo. <br><br>"+
	"Aenean vel eros tristique, molestie urna sit amet, mollis urna. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque a ex posuere, dignissim turpis eget, feugiat nulla. In hac habitasse platea dictumst. Etiam tincidunt vitae nisl congue commodo. Integer tincidunt dolor nisi, ac sollicitudin metus rutrum et. Ut arcu magna, ultricies ut libero ut, posuere condimentum lorem. Integer eget luctus ex. Nam fermentum quis quam vel sagittis. Aliquam semper, sem sit amet luctus pretium, eros justo porttitor dolor, at rutrum quam tellus nec sem. Etiam eu lacus vitae felis dignissim tincidunt nec nec sem. <br><br>"+
	"Vivamus vitae varius ligula. Proin in malesuada ex. In mi mi, dictum at orci in, mattis imperdiet risus. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Vestibulum lorem nibh, laoreet interdum magna pretium, laoreet faucibus mauris. Nam suscipit quam ut velit dapibus mollis. In a nunc consequat nulla sollicitudin luctus vitae a justo. Morbi id turpis dapibus, aliquam ligula in, dictum lacus. Praesent id mattis mi. Donec facilisis tristique mi eget pulvinar. Phasellus viverra vehicula ligula, nec imperdiet massa sagittis in. Sed eu leo tempor tortor elementum rutrum at at augue. <br><br>"+
	"Suspendisse potenti. Ut quis libero ullamcorper, consequat mauris non, egestas velit. Phasellus vitae pretium mi, non feugiat eros. Vestibulum hendrerit turpis gravida accumsan ullamcorper. Aliquam erat volutpat. Maecenas ornare velit id nisl vehicula, et auctor tellus dictum. Maecenas rhoncus orci ac dolor rhoncus tincidunt. Sed venenatis ac sapien at aliquet. Sed non nunc varius, eleifend lectus sit amet, euismod nibh. Quisque suscipit, orci eu molestie ullamcorper, nulla mi elementum lectus, a faucibus tortor massa eu turpis. Fusce sollicitudin, massa eu feugiat bibendum, magna dui dictum ante, vitae dictum eros tortor sit amet nulla. <br><br>"+
	"Pellentesque consequat sit amet nunc id pellentesque. Praesent in libero vel justo facilisis tincidunt a vitae mi. Cras fermentum urna a orci tincidunt, vitae sollicitudin nulla euismod. Pellentesque ac leo ullamcorper, suscipit elit sed, scelerisque odio. Sed sodales dolor quis ornare pretium. Donec ut viverra nisi, in laoreet ex. Praesent ultrices augue sit amet nunc vehicula, et rutrum metus sagittis. Sed aliquam mattis dolor, a cursus risus posuere vel. Suspendisse condimentum tellus dui, quis vehicula lacus tempus in. Vestibulum ac orci nec purus faucibus imperdiet. Suspendisse fringilla facilisis mauris non congue. In a ante quis velit ultricies varius a in justo. Donec tincidunt auctor egestas. Donec et felis nec nisi pharetra viverra eu ac metus. <br><br>"+
	"Cras euismod nibh eget nibh mollis efficitur sed pulvinar leo. Aenean vel eros tristique, molestie urna sit amet, mollis urna.",
        date: new Date(),
        author:	"Peter Schiff",
        level: "Nocoiner",
        views: 0,
        likes: 0,
        dislikes: 0
    },
    
]